[package]

name = "rust_playground"
version = "0.0.1"
authors = ["David Irvine <david.irvine@maidsafe.net>"]

[dependencies]
rust-crypto = "*"
semver = "0.1.14"
#getopts = "0.0.0"
rand = "0.1.3"
#conrod = "0.0.0"
iron = "*"
